<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Countries extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

        $countries = array(
            array('name' => "Afghanistan", 'code' => "AFG"),
            array('name' => "Albania", 'code' => "ALB"),
            array('name' => "Algeria", 'code' => "DZA"),
            array('name' => "Andorra", 'code' => "AND"),
            array('name' => "Angola", 'code' => "AGO"),
            array('name' => "Anguilla", 'code' => "AIA"),
            array('name' => "Antigua and Barbuda", 'code' => "ATG"),
            array('name' => "Argentina", 'code' => "ARG"),
            array('name' => "Armenia", 'code' => "ARM"),
            array('name' => "Aruba", 'code' => "ABW"),
            array('name' => "Australia", 'code' => "AUS"),
            array('name' => "Austria", 'code' => "AUT"),
            array('name' => "Azerbaijan", 'code' => "AZE"),
            array('name' => "Bahamas", 'code' => "BHS"),
            array('name' => "Bahrain", 'code' => "BHR"),
            array('name' => "Bangladesh", 'code' => "BGD"),
            array('name' => "Barbados", 'code' => "BRB"),
            array('name' => "Belarus", 'code' => "BLR"),
            array('name' => "Belgium", 'code' => "BEL"),
            array('name' => "Belize", 'code' => "BLZ"),
            array('name' => "Benin", 'code' => "BEN"),
            array('name' => "Bermuda", 'code' => "BMU"),
            array('name' => "Bhutan", 'code' => "BTN"),
            array('name' => "Bolivia", 'code' => "BOL"),
            array('name' => "Bosnia", 'code' => "BIH"),
            array('name' => "Botswana", 'code' => "BWA"),
            array('name' => "Brazil", 'code' => "BRA"),
            array('name' => "British Virgin Islands", 'code' => "VGB"),
            array('name' => "Brunei", 'code' => "BRN"),
            array('name' => "Bulgaria", 'code' => "BGR"),
            array('name' => "Burkina Faso", 'code' => "BFA"),
            array('name' => "Burundi", 'code' => "BDI"),
            array('name' => "Cabo Verde", 'code' => "CPV"),
            array('name' => "Cambodia", 'code' => "KHM"),
            array('name' => "Cameroon", 'code' => "CMR"),
            array('name' => "Canada", 'code' => "CAN"),
            array('name' => "Caribbean Netherlands", 'code' => "BES"),
            array('name' => "Cayman Islands", 'code' => "CYM"),
            array('name' => "Central African Republic", 'code' => "CAF"),
            array('name' => "Chad", 'code' => "TCD"),
            array('name' => "Channel Islands", 'code' => "JEY"),
            array('name' => "Chile", 'code' => "CHL"),
            array('name' => "China", 'code' => "CHN"),
            array('name' => "Colombia", 'code' => "COL"),
            array('name' => "Comoros", 'code' => "COM"),
            array('name' => "Congo", 'code' => "COG"),
            array('name' => "Costa Rica", 'code' => "CRI"),
            array('name' => "Croatia", 'code' => "HRV"),
            array('name' => "Cuba", 'code' => "CUB"),
            array('name' => "Curaçao", 'code' => "CUW"),
            array('name' => "Cyprus", 'code' => "CYP"),
            array('name' => "Czechia", 'code' => "CZE"),
            array('name' => "Côte d'Ivoire", 'code' => "CIV"),
            array('name' => "DRC", 'code' => "COD"),
            array('name' => "Denmark", 'code' => "DNK"),
            array('name' => "Djibouti", 'code' => "DJI"),
            array('name' => "Dominica", 'code' => "DMA"),
            array('name' => "Dominican Republic", 'code' => "DOM"),
            array('name' => "Ecuador", 'code' => "ECU"),
            array('name' => "Egypt", 'code' => "EGY"),
            array('name' => "El Salvador", 'code' => "SLV"),
            array('name' => "Equatorial Guinea", 'code' => "GNQ"),
            array('name' => "Eritrea", 'code' => "ERI"),
            array('name' => "Estonia", 'code' => "EST"),
            array('name' => "Ethiopia", 'code' => "ETH"),
            array('name' => "Falkland Islands (Malvinas)", 'code' => "FLK"),
            array('name' => "Faroe Islands", 'code' => "FRO"),
            array('name' => "Fiji", 'code' => "FJI"),
            array('name' => "Finland", 'code' => "FIN"),
            array('name' => "France", 'code' => "FRA"),
            array('name' => "French Guiana", 'code' => "GUF"),
            array('name' => "French Polynesia", 'code' => "PYF"),
            array('name' => "Gabon", 'code' => "GAB"),
            array('name' => "Gambia", 'code' => "GMB"),
            array('name' => "Georgia", 'code' => "GEO"),
            array('name' => "Germany", 'code' => "DEU"),
            array('name' => "Ghana", 'code' => "GHA"),
            array('name' => "Gibraltar", 'code' => "GIB"),
            array('name' => "Greece", 'code' => "GRC"),
            array('name' => "Greenland", 'code' => "GRL"),
            array('name' => "Grenada", 'code' => "GRD"),
            array('name' => "Guadeloupe", 'code' => "GLP"),
            array('name' => "Guatemala", 'code' => "GTM"),
            array('name' => "Guinea", 'code' => "GIN"),
            array('name' => "Guinea-Bissau", 'code' => "GNB"),
            array('name' => "Guyana", 'code' => "GUY"),
            array('name' => "Haiti", 'code' => "HTI"),
            array('name' => "Holy See (Vatican City State)", 'code' => "VAT"),
            array('name' => "Honduras", 'code' => "HND"),
            array('name' => "Hong Kong", 'code' => "HKG"),
            array('name' => "Hungary", 'code' => "HUN"),
            array('name' => "Iceland", 'code' => "ISL"),
            array('name' => "India", 'code' => "IND"),
            array('name' => "Indonesia", 'code' => "IDN"),
            array('name' => "Iran", 'code' => "IRN"),
            array('name' => "Iraq", 'code' => "IRQ"),
            array('name' => "Ireland", 'code' => "IRL"),
            array('name' => "Isle of Man", 'code' => "IMN"),
            array('name' => "Israel", 'code' => "ISR"),
            array('name' => "Italy", 'code' => "ITA"),
            array('name' => "Jamaica", 'code' => "JAM"),
            array('name' => "Japan", 'code' => "JPN"),
            array('name' => "Jordan", 'code' => "JOR"),
            array('name' => "Kazakhstan", 'code' => "KAZ"),
            array('name' => "Kenya", 'code' => "KEN"),
            array('name' => "Kiribati", 'code' => "KIR"),
            array('name' => "Kuwait", 'code' => "KWT"),
            array('name' => "Kyrgyzstan", 'code' => "KGZ"),
            array('name' => "Lao People\"s Democratic Republic", 'code' => "LAO"),
            array('name' => "Latvia", 'code' => "LVA"),
            array('name' => "Lebanon", 'code' => "LBN"),
            array('name' => "Lesotho", 'code' => "LSO"),
            array('name' => "Liberia", 'code' => "LBR"),
            array('name' => "Libyan Arab Jamahiriya", 'code' => "LBY"),
            array('name' => "Liechtenstein", 'code' => "LIE"),
            array('name' => "Lithuania", 'code' => "LTU"),
            array('name' => "Luxembourg", 'code' => "LUX"),
            array('name' => "Macao", 'code' => "MAC"),
            array('name' => "Macedonia", 'code' => "MKD"),
            array('name' => "Madagascar", 'code' => "MDG"),
            array('name' => "Malawi", 'code' => "MWI"),
            array('name' => "Malaysia", 'code' => "MYS"),
            array('name' => "Maldives", 'code' => "MDV"),
            array('name' => "Mali", 'code' => "MLI"),
            array('name' => "Malta", 'code' => "MLT"),
            array('name' => "Marshall Islands", 'code' => "MHL"),
            array('name' => "Martinique", 'code' => "MTQ"),
            array('name' => "Mauritania", 'code' => "MRT"),
            array('name' => "Mauritius", 'code' => "MUS"),
            array('name' => "Mayotte", 'code' => "MYT"),
            array('name' => "Mexico", 'code' => "MEX"),
            array('name' => "Micronesia", 'code' => "FSM"),
            array('name' => "Moldova", 'code' => "MDA"),
            array('name' => "Monaco", 'code' => "MCO"),
            array('name' => "Mongolia", 'code' => "MNG"),
            array('name' => "Montenegro", 'code' => "MNE"),
            array('name' => "Montserrat", 'code' => "MSR"),
            array('name' => "Morocco", 'code' => "MAR"),
            array('name' => "Mozambique", 'code' => "MOZ"),
            array('name' => "Myanmar", 'code' => "MMR"),
            array('name' => "Namibia", 'code' => "NAM"),
            array('name' => "Nepal", 'code' => "NPL"),
            array('name' => "Netherlands", 'code' => "NLD"),
            array('name' => "New Caledonia", 'code' => "NCL"),
            array('name' => "New Zealand", 'code' => "NZL"),
            array('name' => "Nicaragua", 'code' => "NIC"),
            array('name' => "Niger", 'code' => "NER"),
            array('name' => "Nigeria", 'code' => "NGA"),
            array('name' => "Norway", 'code' => "NOR"),
            array('name' => "Oman", 'code' => "OMN"),
            array('name' => "Pakistan", 'code' => "PAK"),
            array('name' => "Palau", 'code' => "PLW"),
            array('name' => "Palestine", 'code' => "PSE"),
            array('name' => "Panama", 'code' => "PAN"),
            array('name' => "Papua New Guinea", 'code' => "PNG"),
            array('name' => "Paraguay", 'code' => "PRY"),
            array('name' => "Peru", 'code' => "PER"),
            array('name' => "Philippines", 'code' => "PHL"),
            array('name' => "Poland", 'code' => "POL"),
            array('name' => "Portugal", 'code' => "PRT"),
            array('name' => "Qatar", 'code' => "QAT"),
            array('name' => "Romania", 'code' => "ROU"),
            array('name' => "Russia", 'code' => "RUS"),
            array('name' => "Rwanda", 'code' => "RWA"),
            array('name' => "Réunion", 'code' => "REU"),
            array('name' => "S. Korea", 'code' => "KOR"),
            array('name' => "Saint Helena", 'code' => "SHN"),
            array('name' => "Saint Kitts and Nevis", 'code' => "KNA"),
            array('name' => "Saint Lucia", 'code' => "LCA"),
            array('name' => "Saint Martin", 'code' => "MAF"),
            array('name' => "Saint Pierre Miquelon", 'code' => "SPM"),
            array('name' => "Saint Vincent and the Grenadines", 'code' => "VCT"),
            array('name' => "Samoa", 'code' => "WSM"),
            array('name' => "San Marino", 'code' => "SMR"),
            array('name' => "Sao Tome and Principe", 'code' => "STP"),
            array('name' => "Saudi Arabia", 'code' => "SAU"),
            array('name' => "Senegal", 'code' => "SEN"),
            array('name' => "Serbia", 'code' => "SRB"),
            array('name' => "Seychelles", 'code' => "SYC"),
            array('name' => "Sierra Leone", 'code' => "SLE"),
            array('name' => "Singapore", 'code' => "SGP"),
            array('name' => "Sint Maarten", 'code' => "SXM"),
            array('name' => "Slovakia", 'code' => "SVK"),
            array('name' => "Slovenia", 'code' => "SVN"),
            array('name' => "Solomon Islands", 'code' => "SLB"),
            array('name' => "Somalia", 'code' => "SOM"),
            array('name' => "South Africa", 'code' => "ZAF"),
            array('name' => "South Sudan", 'code' => "SSD"),
            array('name' => "Spain", 'code' => "ESP"),
            array('name' => "Sri Lanka", 'code' => "LKA"),
            array('name' => "St. Barth", 'code' => "BLM"),
            array('name' => "Sudan", 'code' => "SDN"),
            array('name' => "Suriname", 'code' => "SUR"),
            array('name' => "Swaziland", 'code' => "SWZ"),
            array('name' => "Sweden", 'code' => "SWE"),
            array('name' => "Switzerland", 'code' => "CHE"),
            array('name' => "Syrian Arab Republic", 'code' => "SYR"),
            array('name' => "Taiwan", 'code' => "TWN"),
            array('name' => "Tajikistan", 'code' => "TJK"),
            array('name' => "Tanzania", 'code' => "TZA"),
            array('name' => "Thailand", 'code' => "THA"),
            array('name' => "Timor-Leste", 'code' => "TLS"),
            array('name' => "Togo", 'code' => "TGO"),
            array('name' => "Tonga", 'code' => "TON"),
            array('name' => "Trinidad and Tobago", 'code' => "TTO"),
            array('name' => "Tunisia", 'code' => "TUN"),
            array('name' => "Turkey", 'code' => "TUR"),
            array('name' => "Turks and Caicos Islands", 'code' => "TCA"),
            array('name' => "UAE", 'code' => "ARE"),
            array('name' => "UK", 'code' => "GBR"),
            array('name' => "USA", 'code' => "USA"),
            array('name' => "Uganda", 'code' => "UGA"),
            array('name' => "Ukraine", 'code' => "UKR"),
            array('name' => "Uruguay", 'code' => "URY"),
            array('name' => "Uzbekistan", 'code' => "UZB"),
            array('name' => "Vanuatu", 'code' => "VUT"),
            array('name' => "Venezuela", 'code' => "VEN"),
            array('name' => "Vietnam", 'code' => "VNM"),
            array('name' => "Wallis and Futuna", 'code' => "WLF"),
            array('name' => "Western Sahara", 'code' => "ESH"),
            array('name' => "Yemen", 'code' => "YEM"),
            array('name' => "Zambia", 'code' => "ZMB"),
            array('name' => "Zimbabwe", 'code' => "ZWE")

        );

        DB::table("countries")->insert($countries);
    }
}
